### ISSUE TITLE
BMP 

### ISSUE THREAD

**Issue by itsdavidmandal** [orionspacenepal/EDUCAN-Mini-Software-Public#1]
In the BMP code file, line 20. 
The pressure cant be used as a function bhandai cha . 
And in line 18 hola,semi colon missing cha . Fix them hai . 
*Bug found during the cansat workshop.

**Comment by goku-g** [comment]
Thank you for your recommendation!
There is an extra parenthesis and a missing semicolon. We will update it soon.
